[env:wemos_d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    arduino-libraries/NTPClient @ ^3.2.1
    tzapu/WiFiManager @ ^2.0.17
    adafruit/Adafruit GFX Library @ ^1.11.11
    https://github.com/markruys/arduino-Max72xxPanel.git
